import {appSchema, tableSchema} from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'users',
      columns: [
        {name: 'nickname', type: 'string'},
        {name: 'avatar_char', type: 'string'},
        {name: 'du_number', type: 'string'},
        {name: 'hometown_id', type: 'string', isOptional: true},
        {name: 'current_city_id', type: 'string', isOptional: true},
        {name: 'current_city_arrival', type: 'number', isOptional: true},
        {name: 'created_at', type: 'number'},
        {name: 'daily_reminder_time', type: 'string'},
        {name: 'letter_reminder_on', type: 'boolean'},
        {name: 'theme', type: 'string'},
        {name: 'passcode_on', type: 'boolean'},
        {name: 'dark_mode', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'places',
      columns: [
        {name: 'name', type: 'string'},
        {name: 'ch_char', type: 'string'},
        {name: 'pinyin', type: 'string'},
        {name: 'color_hex', type: 'string'},
        {name: 'type', type: 'string', isIndexed: true},
        {name: 'first_visit', type: 'number', isOptional: true},
        {name: 'last_visit', type: 'number', isOptional: true},
        {name: 'visit_count', type: 'number'},
        {name: 'sort_order', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'memories',
      columns: [
        {name: 'type', type: 'string'},
        {name: 'content', type: 'string'},
        {name: 'image_path', type: 'string', isOptional: true},
        {name: 'audio_path', type: 'string', isOptional: true},
        {name: 'audio_duration', type: 'number', isOptional: true},
        {name: 'ink_image_path', type: 'string', isOptional: true},
        {name: 'place_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'place_detail', type: 'string', isOptional: true},
        {name: 'weather_tag', type: 'string', isOptional: true},
        {name: 'body_tags', type: 'string'},
        {name: 'heart_tags', type: 'string'},
        {name: 'custom_tags', type: 'string'},
        {name: 'photo_tone', type: 'string', isOptional: true},
        {name: 'mood', type: 'string', isOptional: true},
        {name: 'written_at', type: 'number', isIndexed: true},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
        {name: 'is_future_letter', type: 'boolean'},
        {name: 'letter_id', type: 'string', isOptional: true},
        {name: 'deleted', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'letters',
      columns: [
        {name: 'memory_id', type: 'string', isIndexed: true},
        {name: 'sent_at', type: 'number'},
        {name: 'arrive_date', type: 'number', isIndexed: true},
        {name: 'arrive_type', type: 'string'},
        {name: 'to_type', type: 'string'},
        {name: 'to_name', type: 'string'},
        {name: 'status', type: 'string', isIndexed: true},
        {name: 'opened_at', type: 'number', isOptional: true},
        {name: 'reply_memory_id', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'settings',
      columns: [
        {name: 'user_id', type: 'string', isIndexed: true},
        {name: 'theme_mode', type: 'string'},
        {name: 'daily_reminder_on', type: 'boolean'},
        {name: 'daily_reminder_time', type: 'string'},
        {name: 'letter_reminder_on', type: 'boolean'},
        {name: 'biometric_lock_on', type: 'boolean'},
        {name: 'default_city', type: 'string'},
        {name: 'onboarding_completed', type: 'boolean'},
        {name: 'privacy_accepted_at', type: 'number', isOptional: true},
        {name: 'updated_at', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'tags',
      columns: [
        {name: 'category', type: 'string', isIndexed: true},
        {name: 'text', type: 'string'},
        {name: 'color_hex', type: 'string'},
        {name: 'season_hint', type: 'string', isOptional: true},
        {name: 'sort_order', type: 'number'},
      ],
    }),
  ],
});
