import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 13,
  tables: [
    tableSchema({
      name: 'users',
      columns: [
        { name: 'nickname', type: 'string' },
        { name: 'avatar_char', type: 'string' },
        { name: 'avatar_path', type: 'string', isOptional: true },
        { name: 'du_number', type: 'string' },
        { name: 'hometown_id', type: 'string', isOptional: true },
        { name: 'current_city_id', type: 'string', isOptional: true },
        { name: 'current_city_arrival', type: 'number', isOptional: true },
        { name: 'birthday', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'daily_reminder_time', type: 'string' },
        { name: 'letter_reminder_on', type: 'boolean' },
        { name: 'theme', type: 'string' },
        { name: 'passcode_on', type: 'boolean' },
        { name: 'dark_mode', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'places',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'ch_char', type: 'string' },
        { name: 'pinyin', type: 'string' },
        { name: 'color_hex', type: 'string' },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'first_visit', type: 'number', isOptional: true },
        { name: 'last_visit', type: 'number', isOptional: true },
        { name: 'visit_count', type: 'number' },
        { name: 'sort_order', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'memories',
      columns: [
        { name: 'type', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'image_path', type: 'string', isOptional: true },
        { name: 'audio_path', type: 'string', isOptional: true },
        { name: 'audio_duration', type: 'number', isOptional: true },
        { name: 'ink_image_path', type: 'string', isOptional: true },
        { name: 'place_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'place_detail', type: 'string', isOptional: true },
        { name: 'weather_tag', type: 'string', isOptional: true },
        { name: 'body_tags', type: 'string' },
        { name: 'heart_tags', type: 'string' },
        { name: 'custom_tags', type: 'string' },
        { name: 'photo_tone', type: 'string', isOptional: true },
        { name: 'mood', type: 'string', isOptional: true },
        { name: 'written_at', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_future_letter', type: 'boolean' },
        { name: 'future_arrive_at', type: 'number', isOptional: true },
        { name: 'future_arrive_type', type: 'string', isOptional: true },
        { name: 'letter_id', type: 'string', isOptional: true },
        { name: 'deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'letters',
      columns: [
        { name: 'memory_id', type: 'string', isIndexed: true },
        { name: 'sent_at', type: 'number' },
        { name: 'arrive_date', type: 'number', isIndexed: true },
        { name: 'arrive_type', type: 'string' },
        { name: 'to_type', type: 'string' },
        { name: 'to_name', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'opened_at', type: 'number', isOptional: true },
        { name: 'reply_memory_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'settings',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'theme_mode', type: 'string' },
        { name: 'art_skin', type: 'string' },
        { name: 'daily_reminder_on', type: 'boolean' },
        { name: 'daily_reminder_time', type: 'string' },
        { name: 'letter_reminder_on', type: 'boolean' },
        { name: 'letter_reminder_time', type: 'string' },
        { name: 'biometric_lock_on', type: 'boolean' },
        { name: 'default_city', type: 'string' },
        { name: 'onboarding_completed', type: 'boolean' },
        { name: 'privacy_accepted_at', type: 'number', isOptional: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'tags',
      columns: [
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'text', type: 'string' },
        { name: 'color_hex', type: 'string' },
        { name: 'season_hint', type: 'string', isOptional: true },
        { name: 'sort_order', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'wishes',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'target_at', type: 'number', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'pinned', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'wish_tapes',
      columns: [
        { name: 'wish_id', type: 'string', isIndexed: true },
        { name: 'text', type: 'string' },
        { name: 'style', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'quests',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'theme_color', type: 'string' },
        { name: 'cover_mode', type: 'string' },
        { name: 'cover_image_asset_id', type: 'string', isOptional: true },
        { name: 'is_template', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'quest_nodes',
      columns: [
        { name: 'quest_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'icon', type: 'string' },
        { name: 'x', type: 'number' },
        { name: 'y', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'quest_edges',
      columns: [
        { name: 'quest_id', type: 'string', isIndexed: true },
        { name: 'from_node_id', type: 'string', isIndexed: true },
        { name: 'to_node_id', type: 'string', isIndexed: true },
        { name: 'style', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'quest_stickies',
      columns: [
        { name: 'quest_id', type: 'string', isIndexed: true },
        { name: 'node_id', type: 'string', isIndexed: true },
        { name: 'text', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'memory_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'collage_pages',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'photo_paths', type: 'string' },
        { name: 'palette', type: 'string' },
        { name: 'layout_seed', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'books',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'subtitle', type: 'string' },
        { name: 'year', type: 'string', isIndexed: true },
        { name: 'categories', type: 'string' },
        { name: 'cover_template', type: 'string' },
        { name: 'cover_bg', type: 'string' },
        { name: 'cover_accent', type: 'string' },
        { name: 'cover_text', type: 'string' },
        { name: 'cover_image_path', type: 'string', isOptional: true },
        { name: 'spine_width', type: 'number' },
        { name: 'source', type: 'string' },
        { name: 'current_page', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'book_pages',
      columns: [
        { name: 'book_id', type: 'string', isIndexed: true },
        { name: 'page_index', type: 'number', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'date_label', type: 'string', isOptional: true },
        { name: 'text_content', type: 'string', isOptional: true },
        { name: 'quote', type: 'string', isOptional: true },
        { name: 'author', type: 'string', isOptional: true },
        { name: 'decoration', type: 'string', isOptional: true },
        { name: 'source_type', type: 'string', isOptional: true },
        { name: 'source_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'scraps',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'text_content', type: 'string' },
        { name: 'source_label', type: 'string' },
        { name: 'source_type', type: 'string', isIndexed: true },
        { name: 'source_id', type: 'string', isOptional: true },
        { name: 'source_book_id', type: 'string', isOptional: true },
        { name: 'color', type: 'string' },
        { name: 'card_type', type: 'string' },
        { name: 'x', type: 'number' },
        { name: 'y', type: 'number' },
        { name: 'rotation', type: 'number' },
        { name: 'tape_color', type: 'string', isOptional: true },
        { name: 'has_letter_line', type: 'boolean' },
        { name: 'archived', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
  ],
});
