import { Platform, StyleSheet } from 'react-native';

import { radius } from '../../tokens/radius';
import { spacing } from '../../tokens/spacing';
import { fontFamilies, fontSizes } from '../../tokens/typography';
import { detailColors } from './MemoryDetailParts';

export const memoryDetailStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: detailColors.background },
  exportStage: {
    position: 'absolute',
    top: 0,
    left: -420,
    width: 360,
  },
  topBar: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.page,
    zIndex: 5,
  },
  collapseButton: {
    minWidth: 48,
    minHeight: 44,
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  collapseText: {
    color: detailColors.inkSoft,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.meta,
    letterSpacing: 2,
  },
  page: { flex: 1 },
  scrollContent: {
    width: '100%',
    maxWidth: 540,
    alignSelf: 'center',
    paddingHorizontal: spacing.page,
  },
  exportPage: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    backgroundColor: detailColors.background,
  },
  contextLabel: {
    alignSelf: 'flex-start',
    marginLeft: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.pill,
    color: detailColors.accent,
    backgroundColor: 'rgba(184, 92, 56, 0.08)',
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
    letterSpacing: 2,
  },
  dateHeader: {
    minHeight: 154,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 28,
    paddingBottom: spacing.lg,
    marginBottom: spacing.xs,
  },
  monthYear: {
    color: detailColors.inkLight,
    fontFamily: fontFamilies.englishSerifItalic,
    fontSize: 12,
    letterSpacing: 3,
  },
  dayNumber: {
    color: detailColors.ink,
    fontFamily: fontFamilies.englishSerif,
    fontSize: 60,
    lineHeight: 60,
    letterSpacing: -1,
    marginTop: spacing.xxs,
  },
  dayMeta: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  dateDot: {
    width: 3,
    height: 3,
    marginHorizontal: spacing.sm,
    borderRadius: radius.round,
    backgroundColor: detailColors.accentSoft,
  },
  weekday: {
    color: detailColors.inkSoft,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.caption,
    letterSpacing: 1,
  },
  lunar: {
    color: detailColors.inkLight,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.caption,
    letterSpacing: 1,
  },
  solarTerm: {
    color: detailColors.inkLight,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.caption,
    letterSpacing: 1,
  },
  seasonSeal: {
    position: 'absolute',
    top: 32,
    right: spacing.sm,
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: detailColors.accentSoft,
    borderRadius: 4,
    opacity: 0.6,
    transform: [{ rotate: '6deg' }],
  },
  seasonSealText: {
    color: detailColors.accent,
    fontFamily: fontFamilies.serif,
    fontSize: 15,
  },
  note: {
    overflow: 'hidden',
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 22,
    backgroundColor: detailColors.note,
    borderRadius: 3,
    boxShadow: '0 8px 24px rgba(59,50,42,0.06)',
  },
  noteRules: {
    position: 'absolute',
    top: 30,
    right: 0,
    bottom: 0,
    left: 0,
  },
  noteRule: {
    height: 1,
    marginTop: 30,
    backgroundColor: 'rgba(192,112,74,0.028)',
  },
  noteHeaderRule: {
    position: 'absolute',
    top: 22,
    right: 28,
    left: 28,
    height: 1,
    backgroundColor: 'rgba(192,112,74,0.12)',
  },
  noteTape: {
    position: 'absolute',
    top: -9,
    left: '37%',
    width: 92,
    height: 22,
    backgroundColor: 'rgba(221,199,159,0.55)',
    transform: [{ rotate: '-2deg' }],
  },
  noteMeta: {
    color: detailColors.inkLight,
    marginBottom: spacing.lg,
    textAlign: 'right',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.caption,
    letterSpacing: 0.3,
  },
  noteBody: {
    color: detailColors.ink,
    fontFamily: fontFamilies.serif,
    fontSize: 15,
    fontStyle: 'italic',
    lineHeight: 28,
    letterSpacing: 0.2,
  },
  emptyBody: {
    color: detailColors.inkLight,
    marginTop: spacing.lg,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.meta,
    fontStyle: 'italic',
  },
  tagLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xxl,
    paddingTop: spacing.md,
    borderTopWidth: 0.6,
    borderTopColor: 'rgba(91,79,68,0.10)',
  },
  tagText: {
    color: detailColors.inkLight,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
  },
  moodText: {
    color: detailColors.accent,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
  },
  thread: {
    minHeight: 190,
    marginTop: 38,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.lg,
  },
  threadEyebrow: {
    color: detailColors.accent,
    fontFamily: fontFamilies.englishSerif,
    fontSize: 11,
    letterSpacing: 2,
  },
  threadTitle: {
    color: detailColors.ink,
    marginTop: spacing.xs,
    marginBottom: spacing.lg,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.title,
  },
  emptyReplies: {
    color: detailColors.inkLight,
    maxWidth: 280,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.meta,
    lineHeight: 23,
  },
  stampStatus: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.xxl,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: 'rgba(255,253,247,0.60)',
    borderWidth: 0.7,
    borderColor: 'rgba(192,112,74,0.20)',
  },
  miniStamp: {
    width: 44,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: detailColors.accent,
    borderStyle: 'dashed',
    transform: [{ rotate: '-4deg' }],
  },
  miniStampText: {
    color: detailColors.accent,
    fontFamily: fontFamilies.serifMedium,
    fontSize: 19,
  },
  stampStatusCopy: { flex: 1 },
  stampStatusTitle: {
    color: detailColors.ink,
    fontFamily: fontFamilies.serifMedium,
    fontSize: fontSizes.meta,
  },
  stampStatusDate: {
    color: detailColors.inkLight,
    marginTop: spacing.xxs,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
  },
  changeStamp: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  changeStampText: {
    color: detailColors.accent,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
  },
  actions: { paddingTop: spacing.lg },
  replyAction: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: detailColors.ink,
    borderRadius: 24,
    boxShadow: '0 2px 10px rgba(59,50,42,0.15)',
  },
  replyActionMark: {
    color: detailColors.accentSoft,
    fontFamily: fontFamilies.sans,
    fontSize: 19,
  },
  replyActionText: {
    color: detailColors.note,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.body,
    letterSpacing: 2,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  secondaryAction: {
    minWidth: 64,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionText: {
    color: detailColors.inkLight,
    fontFamily: fontFamilies.serif,
    fontSize: fontSizes.caption,
  },
  deleteAction: {
    minHeight: 44,
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    paddingHorizontal: spacing.xl,
  },
  deleteActionText: {
    color: '#A24A3B',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.caption,
  },
  saveFeedback: {
    position: 'absolute',
    right: spacing.page,
    bottom: 34,
    width: 184,
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.sm,
    paddingRight: spacing.md,
    backgroundColor: detailColors.note,
    borderWidth: 0.5,
    borderColor: 'rgba(91,79,68,0.14)',
    borderRadius: 5,
    boxShadow: '0 8px 24px rgba(59,50,42,0.18)',
    zIndex: 30,
  },
  saveFeedbackImage: {
    width: 44,
    height: 52,
    backgroundColor: detailColors.background,
    borderRadius: 2,
  },
  saveFeedbackCopy: {
    flex: 1,
  },
  saveFeedbackTitle: {
    color: detailColors.ink,
    fontFamily: fontFamilies.serifMedium,
    fontSize: fontSizes.caption,
  },
  saveFeedbackDetail: {
    color: detailColors.inkLight,
    marginTop: spacing.xxs,
    fontFamily: fontFamilies.serif,
    fontSize: 9,
  },
  androidBottom: {
    paddingBottom: Platform.OS === 'android' ? spacing.lg : 0,
  },
  cornerMark: {
    position: 'absolute',
    right: 7,
    bottom: 6,
    width: 8,
    height: 8,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(192,112,74,0.18)',
  },
  round: { borderRadius: radius.round },
});
